spring.application.name=backend.energyos


# informações sobre o banco de dados e API integrador
influx.token=S4q1c6KBZEMt-NfpePUpAYcxznUH5SD14zldOLuFZiciDY_fO_cN_OTuHJzecsDvbTBP5nT929uCgv8FVpIdAg==
influx.bucket=energyosDB